Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

Layout/LineLength:
  Max: 200

AllCops:
  NewCops: enable